# GemAI — RAG Evaluation v2

### Objective

Re-evaluate GemAI **as the app actually runs today**, and test whether the structure-aware chunker in `lib/seed.ts` beats the plain character splitter.

`rag-evaluation.ipynb` (v1) chose the prose chunk size (800/100) and `topK` (8). Since then the app has changed in ways v1 doesn't measure:

| | v1 | App now |
|---|---|---|
| Chunking | LangChain `RecursiveCharacterTextSplitter(800, 100)` | Structure-aware: one chunk per USGS fact-sheet entry, labelled Smithsonian catalog rows, sentence-aligned prose that can cross pages, caption/boilerplate cleanup |
| Retrieval | k = 4 baseline | k = 8 |
| Prompt | Context-stuffing prompt | Tool call returning numbered passages, inline `[n]` citations, small-talk and off-topic rules |
| Groundedness | Judged without seeing the retrieved passages (so it measured general factual accuracy) | — |

### What this notebook does

1. Loads the **app's own chunks** (from `lib/seed.ts --dry-run`) and, for comparison, the old splitter's chunks.
2. Builds a 19-question dataset: v1's 10 questions (three references corrected against the PDFs) plus questions aimed at the fact sheet, the catalog, tables, and three questions the corpus can't answer.
3. Reproduces the app's answer step: the **system prompt, tool description, titles and k are read from `app/api/chat/route.ts`**, and passages are passed back as a tool result, as in the app.
4. Scores five metrics in LangSmith: correctness, helpfulness, groundedness **against the retrieved passages**, citation accuracy, and retrieval hit rate.
5. Compares old vs new chunking at k = 8, and the new chunking at k = 4.
6. Tests the tool-call decision (search or not) against the running app.

### Running it

- `.env.local` at the repo root needs `OPENAI_API_KEY` and `LANGCHAIN_API_KEY` (anything missing is asked for).
- `npm install` (Part 1 runs the TypeScript chunker).
- Part 6 needs the app running: `npm run dev` (or set `APP_URL`).

## Part 0: Setup

In [1]:
import json
import os
import re
import subprocess
from getpass import getpass
from pathlib import Path

from dotenv import load_dotenv

REPO = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
load_dotenv(REPO / ".env.local")

for key in ["OPENAI_API_KEY", "LANGCHAIN_API_KEY"]:
    if not os.environ.get(key):
        os.environ[key] = getpass(f"{key}: ")

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ.setdefault("LANGCHAIN_PROJECT", "GemAI-Eval-v2")
print(f"Repo: {REPO}")
print(f"LangSmith project: {os.environ['LANGCHAIN_PROJECT']}")

Repo: /home/celine/AIM/notebooks/graded-mini-projects/14
LangSmith project: GemAI-Eval-v2

### Read the app's configuration

The prompt, tool description, document titles and `topK` come straight from the route handler, so this notebook can't drift from the app.

In [2]:
route = (REPO / "app/api/chat/route.ts").read_text()

SYSTEM_PROMPT = re.search(r"system:\s*`([\s\S]*?)`", route).group(1)
TOOL_DESCRIPTION = re.search(r"getInformation: tool\(\{\s*description:\s*'([^']+)'", route).group(1)
SOURCE_TITLES = dict(re.findall(r"'([\w.-]+\.pdf)':\s*'([^']+)'", route))
APP_TOP_K = int(re.search(r"topK:\s*(\d+)", route).group(1))
APP_MODEL = re.search(r"openai\('([\w.-]+)'\)", route).group(1)
APP_EMBEDDING = re.search(r"openai\.embedding\('([\w.-]+)'\)", route).group(1)
APP_MAX_TOKENS = int(re.search(r"maxTokens:\s*(\d+)", route).group(1))
temperature = re.search(r"temperature:\s*([\d.]+)", route)
APP_TEMPERATURE = float(temperature.group(1)) if temperature else None  # None = API default

print(f"Model: {APP_MODEL} | temperature: {APP_TEMPERATURE} | Embedding: {APP_EMBEDDING} | topK: {APP_TOP_K} | maxTokens: {APP_MAX_TOKENS}")
print(f"Titles: {SOURCE_TITLES}")
print(f"\nSystem prompt ({len(SYSTEM_PROMPT)} chars):\n{SYSTEM_PROMPT[:400]}…")

Model: gpt-4.1-mini | temperature: 0.0 | Embedding: text-embedding-3-small | topK: 8 | maxTokens: 1024
Titles: {'usgs-natural-gemstones.pdf': 'USGS — Natural Gemstones', 'usgs-gemstones-mcs-2026.pdf': 'USGS — Mineral Commodity Summaries 2026: Gemstones', 'smithsonian-gems.pdf': 'Smithsonian — Gems in the Smithsonian Institution'}

System prompt (2213 chars):
You are GemAI, a friendly and knowledgeable assistant specializing in gemstones.
Your knowledge comes from USGS gemstone publications and the Smithsonian Institution gem collection reference.

Decide which kind of message you received:
1. Greetings, thanks, small talk, or questions about what you can do: reply briefly and warmly WITHOUT calling any tool, and suggest a few things to ask about (e.g.…

## Part 1: Chunks

- **A — old splitter:** PyMuPDF pages → `RecursiveCharacterTextSplitter(800, 100)`, as in v1.
- **B — app chunker:** exactly what `npm run seed` indexes, via `npx tsx lib/seed.ts --dry-run`.

In [3]:
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

# B: the app's chunks
proc = subprocess.run(["npx", "tsx", "lib/seed.ts", "--dry-run"], cwd=REPO, capture_output=True, text=True)
if proc.returncode != 0:
    raise RuntimeError(proc.stderr or proc.stdout)
app_chunks = json.loads((REPO / "chunks.dry-run.json").read_text())
docs_b = [
    Document(page_content=c["text"], metadata={"source": c["source"], "page": c["page"], "pageEnd": c["pageEnd"]})
    for c in app_chunks
]

# A: the old splitter
pages = []
for pdf in sorted((REPO / "data").glob("*.pdf")):
    for d in PyMuPDFLoader(str(pdf)).load():
        page = d.metadata["page"] + 1  # PyMuPDF pages are 0-based
        pages.append(Document(page_content=d.page_content, metadata={"source": pdf.name, "page": page, "pageEnd": page}))
docs_a = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100).split_documents(pages)

print(f"A (old splitter): {len(docs_a)} chunks")
print(f"B (app chunker):  {len(docs_b)} chunks")

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

A (old splitter): 205 chunks
B (app chunker):  204 chunks

/home/celine/AIM/notebooks/graded-mini-projects/14/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/pdf.py:322: UserWarning: Warning: Empty content on page 19 of document /home/celine/AIM/notebooks/graded-mini-projects/14/data/usgs-natural-gemstones.pdf
  warnings.warn(

Same content, chunked both ways: the Smithsonian catalog row for the Hope Diamond.

In [4]:
def show(docs, needle, label):
    d = next(d for d in docs if needle in d.page_content)
    i = d.page_content.index(needle)
    print(f"--- {label} ({d.metadata['source']} p.{d.metadata['page']}) ---")
    print(d.page_content[max(0, i - 250): i + 150], "\n")

show(docs_a, "(The Hope)", "A")
show(docs_b, "(The Hope)", "B")

--- A (smithsonian-gems.pdf p.32) ---
iption, if any;
place of origin; and U. S. National Museum catalog number and name of
donor. Gems in the Lea and Roebling collections usually are indicated by
the letters “L” and “R.”
DIAMOND
127, colorless (The Portuguese), Brazil (3398)
44.5, blue (The Hope), India (3551, Winston)
18.3, yellow (The Shephard), South Africa (3406)
2.9, pink, Tanzania (3772, De Young)
CORUNDUM: Ruby
50, red-violet

--- B (smithsonian-gems.pdf p.32) ---
Smithsonian collection list — DIAMOND (weight in carats, color, origin (catalog number, donor or collection: L = Lea, R = Roebling))
127, colorless (The Portuguese), Brazil (3398)
44.5, blue (The Hope), India (3551, Winston)
18.3, yellow (The Shephard), South Africa (3406)
2.9, pink, Tanzania (3772, De Young)

## Part 2: Evaluation dataset

19 questions. Every reference was checked against the PDF text, and `expected` lists where the answer is (file, page) for the retrieval metric.

Changes to v1's 10 questions:
- **Hope Diamond:** reference now includes 44.5 carats, blue, India (Smithsonian collection list, p.32).
- **Gem cuts:** v1 listed "tumbled stones" as a cut; the source says tumbled stones are only smoothed. Brilliant and step cuts are the commonest; cabochons for opaque and star stones.
- **Pegmatites:** v1's reference came from the *stream gravels* definition and implied emeralds come from pegmatites; the Smithsonian text says the finest emeralds do not.
- **Specific gravity, synthetics:** wording aligned with the source.

New questions target structures the chunker handles specially (fact sheet, catalog, birthstone table, the commodity summary) and three questions the corpus does not answer (`expected` empty). "Where is tanzanite mined?" is a trap: the corpus mentions Tanzania (diamond production, a Tanzanian pink diamond) but never tanzanite, and `gpt-4o-mini` used that to invent a cited answer.

In [5]:
import hashlib

import pandas as pd

NG = "usgs-natural-gemstones.pdf"
SG = "smithsonian-gems.pdf"
MCS = "usgs-gemstones-mcs-2026.pdf"

test_data = [
    # --- v1 questions ---
    {"category": "v1", "question": "What is the hardness of diamond on the Mohs scale?",
     "reference": "Diamond has a hardness of 10 on the Mohs scale, the highest on the scale; it is the hardest substance known.",
     "expected": [[NG, 7], [SG, 12]]},
    {"category": "v1", "question": "Where were sapphires first found in Montana?",
     "reference": "Sapphires in Judith Basin County, Montana, were first found when the gravels were worked for gold from 1895 to 1930.",
     "expected": [[NG, 4]]},
    {"category": "v1", "question": "What is the Hope Diamond?",
     "reference": "The Hope Diamond is a 44.5-carat blue diamond from India in the Smithsonian's National Gem Collection, given by Harry Winston, Inc.",
     "expected": [[SG, 32], [SG, 2]]},
    {"category": "v1", "question": "What makes a mineral qualify as a gemstone?",
     "reference": "A gemstone is a mineral, stone, or organic matter that can be cut and polished for jewelry or ornament. A precious gemstone has beauty, durability, and rarity; a semiprecious gemstone has only one or two of these qualities.",
     "expected": [[NG, 4]]},
    {"category": "v1", "question": "What is specific gravity and how is it used in gemology?",
     "reference": "Specific gravity is the number of times heavier a gemstone is than an equal volume of water (the ratio of its density to water's). Each gem species has its own specific gravity, which can be measured without harming the stone, so it is a valuable aid in identification.",
     "expected": [[NG, 7], [SG, 4]]},
    {"category": "v1", "question": "How did the Smithsonian gem collection begin?",
     "reference": "The National Gem Collection began in 1884 when Prof. F. W. Clarke, honorary curator of the Division of Mineralogy, prepared an exhibit of American precious stones for the Smithsonian's display at the New Orleans Exposition.",
     "expected": [[SG, 2]]},
    {"category": "v1", "question": "What are the main types of gem cuts?",
     "reference": "Fine gem rough is mainly faceted. The brilliant and step cuts are by far the commonest basic cuts, with fancy cuts such as the baguette also used. Opaque stones and those showing stars or cat's-eyes are cut as cabochons, a raised and rounded form.",
     "expected": [[SG, 6], [SG, 7]]},
    {"category": "v1", "question": "What is the difference between a natural and synthetic gemstone?",
     "reference": "A synthetic gemstone is made in the laboratory and, to qualify as synthetic, must be identical chemically and structurally with its natural counterpart, which formed in nature. Synthetic sapphire, ruby, spinel, emerald, and rutile are produced commercially.",
     "expected": [[SG, 9]]},
    {"category": "v1", "question": "What gemstones are found in pegmatite deposits?",
     "reference": "Pegmatites are very coarse-grained igneous (granite) rocks. Beryl is usually found in pegmatites, sometimes as very large crystals, but the finest emeralds are not found in pegmatites.",
     "expected": [[SG, 17], [NG, 4]]},
    {"category": "v1", "question": "What was the combined value of US gemstone production in 2025?",
     "reference": "The combined value of U.S. natural and synthetic gemstone output in 2025 was an estimated $47 million, a decrease of 30% compared with 2024.",
     "expected": [[MCS, 1]]},
    # --- fact sheet ---
    {"category": "fact sheet", "question": "What is the hardness of feldspar?",
     "reference": "Feldspar has a hardness of 6 to 6.5 on the Mohs scale.",
     "expected": [[NG, 7]]},
    {"category": "fact sheet", "question": "What colors does spinel come in?",
     "reference": "Spinel varieties include balas ruby (red), almandine spinel (purple red), rubicelle (orange), sapphire spinel and gahnospinel (blue), and chlorspinel (green).",
     "expected": [[NG, 8], [NG, 9], [SG, 21]]},
    # --- catalog ---
    {"category": "catalog", "question": "How many carats is the Hope Diamond?",
     "reference": "The Hope Diamond weighs 44.5 carats.",
     "expected": [[SG, 32]]},
    {"category": "catalog", "question": "What is the largest topaz in the Smithsonian collection list?",
     "reference": "The largest topaz listed is a 7725-carat yellow topaz from Brazil.",
     "expected": [[SG, 33]]},
    # --- tables ---
    {"category": "table", "question": "What is the birthstone for October?",
     "reference": "The birthstone for October is opal or tourmaline.",
     "expected": [[NG, 10], [SG, 11]]},
    {"category": "table", "question": "Where does the US import most of its diamonds from?",
     "reference": "From 2021 to 2024, by value, U.S. diamond imports came from India (46%), Israel (27%), Belgium (11%), South Africa (4%), and other countries (12%).",
     "expected": [[MCS, 1], [MCS, 2]]},
    # --- not in the corpus ---
    {"category": "unanswerable", "question": "How much does a carat of tanzanite cost?",
     "reference": "The sources do not contain information about tanzanite or its price.",
     "expected": []},
    {"category": "unanswerable", "question": "Where is tanzanite mined?",
     "reference": "The sources do not contain information about tanzanite or where it is mined.",
     "expected": []},
    {"category": "unanswerable", "question": "What is the hardness of moissanite?",
     "reference": "The sources do not contain information about moissanite.",
     "expected": []},
]

df = pd.DataFrame(test_data)
print(f"{len(df)} questions:", df["category"].value_counts().to_dict())
df[["category", "question", "reference"]]

19 questions: {'v1': 10, 'unanswerable': 3, 'fact sheet': 2, 'catalog': 2, 'table': 2}

,category,question,reference
0,v1,What is the hardness of diamond on the Mohs sc...,Diamond has a hardness of 10 on the Mohs scale...
1,v1,Where were sapphires first found in Montana?,"Sapphires in Judith Basin County, Montana, wer..."
2,v1,What is the Hope Diamond?,The Hope Diamond is a 44.5-carat blue diamond ...
3,v1,What makes a mineral qualify as a gemstone?,"A gemstone is a mineral, stone, or organic mat..."
4,v1,What is specific gravity and how is it used in...,Specific gravity is the number of times heavie...
5,v1,How did the Smithsonian gem collection begin?,The National Gem Collection began in 1884 when...
6,v1,What are the main types of gem cuts?,Fine gem rough is mainly faceted. The brillian...
7,v1,What is the difference between a natural and s...,A synthetic gemstone is made in the laboratory...
8,v1,What gemstones are found in pegmatite deposits?,Pegmatites are very coarse-grained igneous (gr...
9,v1,What was the combined value of US gemstone pro...,The combined value of U.S. natural and synthet...
10,fact sheet,What is the hardness of feldspar?,Feldspar has a hardness of 6 to 6.5 on the Moh...
11,fact sheet,What colors does spinel come in?,"Spinel varieties include balas ruby (red), alm..."
12,catalog,How many carats is the Hope Diamond?,The Hope Diamond weighs 44.5 carats.
13,catalog,What is the largest topaz in the Smithsonian c...,The largest topaz listed is a 7725-carat yello...
14,table,What is the birthstone for October?,The birthstone for October is opal or tourmaline.
15,table,Where does the US import most of its diamonds ...,"From 2021 to 2024, by value, U.S. diamond impo..."
16,unanswerable,How much does a carat of tanzanite cost?,The sources do not contain information about t...
17,unanswerable,Where is tanzanite mined?,The sources do not contain information about t...
18,unanswerable,What is the hardness of moissanite?,The sources do not contain information about m...

In [6]:
from langsmith import Client

client = Client()

# The dataset name includes a hash of its contents, so editing test_data creates a new
# dataset instead of silently reusing a stale one, and re-running reuses the same one.
digest = hashlib.sha1(json.dumps(test_data, sort_keys=True).encode()).hexdigest()[:8]
DATASET_NAME = f"GemAI Eval v2 ({digest})"

if client.has_dataset(dataset_name=DATASET_NAME):
    dataset = client.read_dataset(dataset_name=DATASET_NAME)
    print(f"Reusing dataset: {DATASET_NAME}")
else:
    dataset = client.create_dataset(DATASET_NAME, description="GemAI v2: app chunker vs old splitter")
    client.create_examples(
        inputs=[{"question": t["question"]} for t in test_data],
        outputs=[{"answer": t["reference"], "expected": t["expected"]} for t in test_data],
        metadata=[{"category": t["category"]} for t in test_data],
        dataset_id=dataset.id,
    )
    print(f"Created dataset: {DATASET_NAME}")

Created dataset: GemAI Eval v2 (72480653)

## Part 3: Pipeline that mirrors the app

In the app, the model calls `getInformation`, the tool returns numbered passages (`id`, `title`, `page`, `pageEnd`, `text`), and the model answers from them. Here the same messages are built explicitly: system prompt → question → tool call → tool result → answer.

Two differences from the app, both deliberate:
- The search query is the question itself; in the app the model writes its own query (usually a close paraphrase).
- Retrieval always happens. Whether the app *decides* to search is tested separately in Part 6.

In [7]:
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore

embeddings = OpenAIEmbeddings(model=APP_EMBEDDING)

stores = {
    "A": QdrantVectorStore.from_documents(docs_a, embeddings, location=":memory:", collection_name="old-splitter"),
    "B": QdrantVectorStore.from_documents(docs_b, embeddings, location=":memory:", collection_name="app-chunker"),
}

GET_INFORMATION = {
    "type": "function",
    "function": {
        "name": "getInformation",
        "description": TOOL_DESCRIPTION,
        "parameters": {
            "type": "object",
            "properties": {"query": {"type": "string", "description": "the topic, term, or sub-question to search for"}},
            "required": ["query"],
        },
    },
}
def make_answer_llm(model):
    # tool_choice="none": the passages are already supplied, so the model must answer.
    llm = ChatOpenAI(model=model, max_tokens=APP_MAX_TOKENS, temperature=APP_TEMPERATURE)
    return llm.bind_tools([GET_INFORMATION], tool_choice="none")


def to_passages(docs):
    return [
        {
            "id": i + 1,
            "text": d.page_content,
            "page": d.metadata["page"],
            "pageEnd": d.metadata["pageEnd"],
            "source": d.metadata["source"],
            "title": SOURCE_TITLES.get(d.metadata["source"], d.metadata["source"]),
        }
        for i, d in enumerate(docs)
    ]


def make_target(store, k, model=APP_MODEL):
    answer_llm = make_answer_llm(model)

    def target(inputs: dict) -> dict:
        question = inputs["question"]
        passages = to_passages(store.similarity_search(question, k=k))
        messages = [
            SystemMessage(SYSTEM_PROMPT),
            HumanMessage(question),
            AIMessage("", tool_calls=[{"name": "getInformation", "args": {"query": question}, "id": "call_1"}]),
            ToolMessage(json.dumps(passages), tool_call_id="call_1"),
        ]
        return {"output": answer_llm.invoke(messages).content, "contexts": passages}

    return target


print(make_target(stores["B"], APP_TOP_K)({"question": "What is the hardness of feldspar?"})["output"])

The hardness of feldspar on the Mohs scale is between 6 and 6.5 [2].

## Part 4: Evaluators

| Metric | Judges | Change from v1 |
|---|---|---|
| `correctness` | Answer vs reference answer | Same (`qa`) |
| `helpfulness` | Helpfulness given the reference | Same |
| `groundedness` | Is every claim supported by **the retrieved passages**? | Fixed: v1 never showed the judge the passages |
| `citation_accuracy` | Share of cited sentences whose cited passage actually supports them | New |
| `retrieval_hit` | Is a passage from an expected page in the top k? (no LLM) | New |

For unanswerable questions, `citation_accuracy` and `retrieval_hit` are skipped; `correctness` checks the bot says the sources don't cover it.

In [8]:
from langsmith.evaluation import LangChainStringEvaluator
from pydantic import BaseModel, Field

eval_llm = ChatOpenAI(model="gpt-4.1", temperature=0)


def passages_text(passages):
    return "\n\n".join(f"[{p['id']}] ({p['title']}, p.{p['page']}) {p['text']}" for p in passages)


def answer_fields(run, example):
    return {
        "prediction": run.outputs["output"],
        "reference": example.outputs["answer"],
        "input": example.inputs["question"],
    }


correctness = LangChainStringEvaluator("qa", config={"llm": eval_llm}, prepare_data=answer_fields)

helpfulness = LangChainStringEvaluator(
    "labeled_criteria",
    config={
        "criteria": {"helpfulness": "Is this submission helpful to the user, taking into account the correct reference answer?"},
        "llm": eval_llm,
    },
    prepare_data=answer_fields,
)

groundedness = LangChainStringEvaluator(
    "labeled_criteria",
    config={
        "criteria": {
            "groundedness": (
                "Is every factual claim in the submission supported by the reference passages? "
                "A claim that is true but not stated in the passages counts as unsupported. "
                "Saying that the passages do not cover something is not a factual claim."
            )
        },
        "llm": eval_llm,
    },
    prepare_data=lambda run, example: {
        "prediction": run.outputs["output"],
        "reference": passages_text(run.outputs["contexts"]),
        "input": example.inputs["question"],
    },
)


class CitationCheck(BaseModel):
    cited_sentences: int = Field(description="Number of sentences or list items that carry at least one [n] citation")
    supported: int = Field(description="How many of those are fully supported by the passage(s) they cite")
    unsupported_examples: list[str] = Field(description="Up to three cited statements their passages do not support")


citation_judge = eval_llm.with_structured_output(CitationCheck)


def citation_accuracy(run, example):
    if not example.outputs["expected"]:
        return {"key": "citation_accuracy", "score": None, "comment": "unanswerable question"}
    answer = run.outputs["output"]
    if not re.search(r"\[\d+", answer):
        return {"key": "citation_accuracy", "score": 0, "comment": "answer has no citations"}
    check = citation_judge.invoke(
        "Check the inline citations in an answer. For each sentence or list item that carries one or more [n] "
        "markers, decide whether the passages it cites support it. Judge only against the cited passages, not "
        f"general knowledge.\n\nPASSAGES:\n{passages_text(run.outputs['contexts'])}\n\nANSWER:\n{answer}"
    )
    if check.cited_sentences == 0:
        return {"key": "citation_accuracy", "score": 0, "comment": "no cited sentences found"}
    return {
        "key": "citation_accuracy",
        "score": min(check.supported, check.cited_sentences) / check.cited_sentences,
        "comment": "; ".join(check.unsupported_examples),
    }


def retrieval_hit(run, example):
    expected = example.outputs["expected"]
    if not expected:
        return {"key": "retrieval_hit", "score": None, "comment": "unanswerable question"}
    hit = any(
        p["source"] == source and p["page"] <= page <= p["pageEnd"]
        for p in run.outputs["contexts"]
        for source, page in expected
    )
    return {"key": "retrieval_hit", "score": int(hit)}


evaluators = [correctness, helpfulness, groundedness, citation_accuracy, retrieval_hit]
print("Evaluators: correctness, helpfulness, groundedness, citation_accuracy, retrieval_hit")

Evaluators: correctness, helpfulness, groundedness, citation_accuracy, retrieval_hit

## Part 5: Experiments

All three use the same dataset, model, prompt and evaluators.

| Experiment | Chunks | k |
|---|---|---|
| `A-old-splitter-k8` | Old splitter | 8 |
| `B-app-chunker-k8` | App chunker (what the app runs) | 8 |
| `B-app-chunker-k4` | App chunker | 4 |

**Hypothesis:** B beats A mainly on fact-sheet and catalog questions (retrieval hit, correctness), because their facts are no longer split from their context; B should also be at least as grounded. If B at k=4 matches B at k=8, the larger k was compensating for poor chunks.

Each experiment runs **`N_REPS` times** (answer generation and judging both repeat). Averages are over all runs, and the spread between runs shows how much of a difference is noise.

In [9]:
from langsmith.evaluation import evaluate

N_REPS = 2

EXPERIMENTS = {
    "A-old-splitter-k8": (stores["A"], 8),
    "B-app-chunker-k8": (stores["B"], 8),
    "B-app-chunker-k4": (stores["B"], 4),
}

results = {}
for name, (store, k) in EXPERIMENTS.items():
    print(f"\n=== {name} ===")
    results[name] = evaluate(
        make_target(store, k),
        data=DATASET_NAME,
        evaluators=evaluators,
        experiment_prefix=name,
        metadata={"chunks": name.split("-k")[0], "k": k, "model": APP_MODEL},
        num_repetitions=N_REPS,
        max_concurrency=4,
    )

=== A-old-splitter-k8 ===

/home/celine/AIM/notebooks/graded-mini-projects/14/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

View the evaluation results for experiment: 'A-old-splitter-k8-8309e1d1' at:
https://smith.langchain.com/o/52420107-7b88-4243-acba-2f92a36f9bc4/datasets/822dec15-b523-4bde-b365-8caa17350b91/compare?selectedSessions=1e580a65-084f-4ea7-bf0b-45651ab085a5

0it [00:00, ?it/s]

1it [00:08,  8.06s/it]

3it [00:08,  2.24s/it]

4it [00:11,  2.52s/it]

5it [00:14,  2.59s/it]

7it [00:15,  1.71s/it]

8it [00:18,  1.92s/it]

10it [00:20,  1.55s/it]

11it [00:23,  1.95s/it]

12it [00:24,  1.75s/it]

13it [00:25,  1.36s/it]

14it [00:28,  1.99s/it]

15it [00:32,  2.38s/it]

16it [00:32,  1.75s/it]

17it [00:35,  2.04s/it]

18it [00:35,  1.67s/it]

19it [00:36,  1.46s/it]

20it [00:37,  1.12s/it]

21it [00:40,  1.88s/it]

23it [00:41,  1.17s/it]

24it [00:42,  1.08s/it]

25it [00:46,  1.93s/it]

26it [00:46,  1.50s/it]

27it [00:47,  1.14s/it]

28it [00:48,  1.31s/it]

29it [00:52,  2.02s/it]

30it [00:53,  1.56s/it]

31it [00:55,  1.70s/it]

32it [00:55,  1.36s/it]

33it [00:59,  2.01s/it]

34it [00:59,  1.59s/it]

35it [01:03,  2.06s/it]

36it [01:04,  1.94s/it]

37it [01:04,  1.45s/it]

38it [01:05,  1.17s/it]

38it [01:05,  1.72s/it]

=== B-app-chunker-k8 ===

View the evaluation results for experiment: 'B-app-chunker-k8-c6836682' at:
https://smith.langchain.com/o/52420107-7b88-4243-acba-2f92a36f9bc4/datasets/822dec15-b523-4bde-b365-8caa17350b91/compare?selectedSessions=bf7809b7-7f53-4e86-a33b-3374d7c5122a

0it [00:00, ?it/s]

1it [00:07,  7.41s/it]

3it [00:07,  2.00s/it]

4it [00:09,  1.91s/it]

5it [00:12,  2.21s/it]

6it [00:12,  1.70s/it]

7it [00:14,  1.68s/it]

9it [00:17,  1.64s/it]

10it [00:19,  1.74s/it]

11it [00:20,  1.44s/it]

13it [00:24,  1.83s/it]

14it [00:26,  1.79s/it]

15it [00:28,  1.89s/it]

16it [00:29,  1.61s/it]

17it [00:30,  1.44s/it]

18it [00:33,  1.92s/it]

19it [00:35,  1.85s/it]

21it [00:35,  1.09s/it]

22it [00:39,  1.70s/it]

23it [00:40,  1.57s/it]

24it [00:42,  1.55s/it]

25it [00:42,  1.26s/it]

26it [00:45,  1.60s/it]

27it [00:46,  1.48s/it]

28it [00:47,  1.33s/it]

29it [00:50,  1.86s/it]

30it [00:52,  1.86s/it]

31it [00:53,  1.59s/it]

32it [00:55,  1.88s/it]

33it [00:59,  2.56s/it]

34it [01:00,  1.95s/it]

35it [01:00,  1.50s/it]

36it [01:01,  1.24s/it]

37it [01:05,  2.13s/it]

38it [01:07,  2.01s/it]

38it [01:07,  1.77s/it]

=== B-app-chunker-k4 ===

View the evaluation results for experiment: 'B-app-chunker-k4-1f027325' at:
https://smith.langchain.com/o/52420107-7b88-4243-acba-2f92a36f9bc4/datasets/822dec15-b523-4bde-b365-8caa17350b91/compare?selectedSessions=12103dc5-2274-4a3a-af02-8b6a6447c3c0

0it [00:00, ?it/s]

1it [00:07,  7.52s/it]

2it [00:07,  3.18s/it]

3it [00:10,  2.84s/it]

4it [00:11,  2.24s/it]

5it [00:11,  1.59s/it]

6it [00:13,  1.71s/it]

7it [00:15,  1.55s/it]

8it [00:18,  2.09s/it]

9it [00:19,  1.90s/it]

10it [00:20,  1.41s/it]

11it [00:20,  1.20s/it]

12it [00:27,  2.75s/it]

13it [00:27,  2.15s/it]

14it [00:28,  1.58s/it]

15it [00:28,  1.17s/it]

16it [00:31,  1.88s/it]

17it [00:33,  1.76s/it]

18it [00:34,  1.45s/it]

19it [00:34,  1.17s/it]

20it [00:37,  1.80s/it]

21it [00:38,  1.45s/it]

22it [00:39,  1.33s/it]

23it [00:40,  1.34s/it]

24it [00:42,  1.46s/it]

25it [00:43,  1.20s/it]

26it [00:47,  2.12s/it]

27it [00:49,  2.02s/it]

28it [00:50,  1.64s/it]

29it [00:50,  1.35s/it]

30it [00:56,  2.81s/it]

31it [00:58,  2.33s/it]

32it [00:58,  1.80s/it]

33it [01:00,  1.75s/it]

34it [01:02,  1.98s/it]

35it [01:04,  1.78s/it]

36it [01:04,  1.40s/it]

37it [01:05,  1.14s/it]

38it [01:10,  2.24s/it]

38it [01:10,  1.84s/it]

### Results

In [10]:
METRICS = ["correctness", "helpfulness", "groundedness", "citation_accuracy", "retrieval_hit"]
category_by_question = {t["question"]: t["category"] for t in test_data}


def to_frame(name, res):
    df = res.to_pandas()
    df["question"] = df["inputs.question"]
    df["category"] = df["question"].map(category_by_question)
    df["experiment"] = name
    df["rep"] = df.groupby("question").cumcount() + 1  # one row per question per repetition
    return df.rename(columns={f"feedback.{m}": m for m in METRICS})


rows = pd.concat([to_frame(name, res) for name, res in results.items()], ignore_index=True)
for m in METRICS:
    rows[m] = pd.to_numeric(rows[m], errors="coerce")

print(f"{len(rows)} scored answers ({len(test_data)} questions × {N_REPS} runs × {len(EXPERIMENTS)} experiments)")
summary = rows.groupby("experiment", sort=False)[METRICS].mean().round(2)
summary

114 scored answers (19 questions × 2 runs × 3 experiments)

,correctness,helpfulness,groundedness,citation_accuracy,retrieval_hit
experiment,,,,,
A-old-splitter-k8,0.95,0.95,0.95,1.00,0.94
B-app-chunker-k8,1.00,1.00,0.95,0.98,1.00
B-app-chunker-k4,0.95,0.92,0.89,0.95,1.00

Average of each run separately. If the runs disagree by about as much as two experiments differ, that difference is noise.

In [11]:
per_run = rows.groupby(["experiment", "rep"], sort=False)[METRICS].mean().round(2)
per_run

                       correctness  helpfulness  groundedness  \
experiment        rep
A-old-splitter-k8 1           0.95         0.95          0.89
                  2           0.95         0.95          1.00
B-app-chunker-k8  1           1.00         1.00          0.95
                  2           1.00         1.00          0.95
B-app-chunker-k4  1           0.95         0.89          0.84
                  2           0.95         0.95          0.95

                       citation_accuracy  retrieval_hit
experiment        rep
A-old-splitter-k8 1                 1.00           0.94
                  2                 1.00           0.94
B-app-chunker-k8  1                 0.97           1.00
                  2                 0.99           1.00
B-app-chunker-k4  1                 0.92           1.00
                  2                 0.98           1.00

How often the two runs of the same experiment scored the same question differently (share of questions). This mixes judge noise with variation in the generated answers.

In [12]:
def disagreement(group):
    pivot = group.pivot_table(index="question", columns="rep", values=METRICS, aggfunc="first")
    return pd.Series({m: (pivot[m].nunique(axis=1, dropna=True) > 1).mean() for m in METRICS})


rows.groupby("experiment", sort=False).apply(disagreement, include_groups=False).round(2)

,correctness,helpfulness,groundedness,citation_accuracy,retrieval_hit
experiment,,,,,
A-old-splitter-k8,0.0,0.00,0.11,0.00,0.0
B-app-chunker-k8,0.0,0.00,0.00,0.11,0.0
B-app-chunker-k4,0.0,0.05,0.11,0.05,0.0

By question type (correctness / retrieval hit):

In [13]:
by_category = (
    rows.groupby(["category", "experiment"], sort=False)[["correctness", "retrieval_hit", "groundedness"]]
    .mean()
    .round(2)
    .unstack("experiment")
)
by_category

                   correctness                                    \
experiment   A-old-splitter-k8 B-app-chunker-k8 B-app-chunker-k4
category
unanswerable               1.0              1.0              1.0
table                      1.0              1.0              0.5
catalog                    0.5              1.0              1.0
fact sheet                 1.0              1.0              1.0
v1                         1.0              1.0              1.0

                 retrieval_hit                                    \
experiment   A-old-splitter-k8 B-app-chunker-k8 B-app-chunker-k4
category
unanswerable               NaN              NaN              NaN
table                      1.0              1.0              1.0
catalog                    0.5              1.0              1.0
fact sheet                 1.0              1.0              1.0
v1                         1.0              1.0              1.0

                  groundedness
experiment   A-old-splitter-k8 B-app-chunker-k8 B-app-chunker-k4
category
unanswerable               1.0              1.0             1.00
table                      1.0              1.0             1.00
catalog                    1.0              1.0             1.00
fact sheet                 1.0              1.0             0.75
v1                         0.9              0.9             0.85

Answers that lost points, for inspection:

In [14]:
pd.set_option("display.max_colwidth", 200)
cols = ["experiment", "rep", "category", "question"] + METRICS + ["outputs.output"]
misses = rows[(rows["correctness"] < 1) | (rows["groundedness"] < 1) | (rows["citation_accuracy"] < 1)]
misses[cols].sort_values(["question", "experiment", "rep"])

,experiment,rep,category,question,correctness,helpfulness,groundedness,citation_accuracy,retrieval_hit,outputs.output
89,B-app-chunker-k4,1,v1,How did the Smithsonian gem collection begin?,1,0,0,0.000000,1.0,"The Smithsonian National Gem Collection began in 1884 when Prof. F. W. Clarke, then honorary curator of the Division of Mineralogy, prepared an exhibit of American precious stones for the Smithson..."
83,B-app-chunker-k4,1,fact sheet,What colors does spinel come in?,1,1,1,0.666667,1.0,"Spinel comes in a variety of colors including purplish red (Almandine spinel), orange-red (Rubicelle), rose red (Balas ruby), deep red (Ruby spinel), translucent grass green (Chlorospinel), opaque..."
105,B-app-chunker-k4,2,fact sheet,What colors does spinel come in?,1,1,1,0.666667,1.0,"Spinel comes in a variety of colors including purplish red (Almandine spinel), orange-red (Rubicelle), rose red (Balas ruby), deep red (Ruby spinel), translucent grass green (Chlorospinel), opaque..."
66,B-app-chunker-k8,2,fact sheet,What colors does spinel come in?,1,1,1,0.777778,1.0,Spinel comes in a wide range of colors. Some varieties and their colors include:\n\n- Almandine spinel: Purplish red\n- Rubicelle: Orange-red\n- Balas ruby: Rose red\n- Ruby spinel: Deep red\n- Ch...
12,A-old-splitter-k8,1,v1,What gemstones are found in pegmatite deposits?,1,1,0,1.000000,1.0,"Gemstones commonly found in pegmatite deposits include beryl, which occurs in very coarse-grained granite rocks formed by cooling molten material beneath the earth's surface. Beryl crystals can be..."
17,A-old-splitter-k8,1,v1,What is the Hope Diamond?,1,1,0,1.000000,1.0,"The Hope Diamond is a famous blue diamond that very likely originated in India, which was the most important source of diamonds until 1728 [2]. It is part of the Smithsonian Institution's gem coll..."
90,B-app-chunker-k4,1,v1,What is the difference between a natural and synthetic gemstone?,1,1,0,1.000000,1.0,"A natural gemstone is formed by geological processes in nature, while a synthetic gemstone is a man-made product created in a laboratory. To qualify as a synthetic gemstone, the man-made product m..."
108,B-app-chunker-k4,2,v1,What is the difference between a natural and synthetic gemstone?,1,1,0,1.000000,1.0,"A natural gemstone is formed by geological processes in nature, while a synthetic gemstone is a man-made product created in a laboratory. To qualify as a synthetic gemstone, the man-made product m..."
85,B-app-chunker-k4,1,fact sheet,What is the hardness of feldspar?,1,1,0,1.000000,1.0,"The hardness of feldspar on the Mohs scale is between 6 and 6.5 [2]. This means feldspar is moderately hard, ranking just below quartz which has a hardness of 7 [1][3]."
6,A-old-splitter-k8,1,catalog,What is the largest topaz in the Smithsonian collection list?,0,0,1,1.000000,0.0,"The sources do not provide a specific mention of the largest topaz in the Smithsonian collection. They do describe topaz as occurring in very large crystals, some weighing several hundred pounds, ..."
27,A-old-splitter-k8,2,catalog,What is the largest topaz in the Smithsonian collection list?,0,0,1,1.000000,0.0,"The sources do not provide a specific mention of the largest topaz in the Smithsonian collection. They do describe topaz as occurring in very large crystals, some weighing several hundred pounds, ..."
79,B-app-chunker-k4,1,table,Where does the US import most of its diamonds from?,0,0,1,1.000000,1.0,"The sources do not specify exactly from which countries the US imports most of its diamonds. However, they do mention that the US is one of the world's leading markets for polished diamonds and th..."
101,B-app-chunker-k4,2,table,Where does the US import most of its diamonds from?,0,0,1,1.000000,1.0,"The sources do not specify exactly from which countries the US imports most of its diamonds. However, they mention that the United States is one of the world's leading markets for polished diamond..."
40,B-app-chunker-k8,1,table,Where does the US import most of its diamonds from?,1,1,1,0.500000,1.0,"The United States imports most of its diamonds from India, which accounts for 46% of diamond imports by value. Other significant sources include Israel with 27%, Belgium with 11%, and South Africa..."
55,B-app-chunker-k8,1,v1,Where were sapphires first found in Montana?,1,1,0,1.000000,1.0,Sapphires were first found in Montana in Judith Basin County when the gravels were worked for gold from 1895 to 1930 [1].
72,B-app-chunker-k8,2,v1,Where were sapphires first found in Montana?,1,1,0,1.000000,1.0,Sapphires were first found in Montana in Judith Basin County when the gravels were worked for gold from 1895 to 1930 [1].

## Part 5b: Model comparison

The app switched from `gpt-4o-mini` to `gpt-4.1-mini`. In manual testing, `gpt-4o-mini` sometimes answered questions the corpus doesn't cover from its own knowledge, with a citation to an unrelated passage (e.g. "Where is tanzanite mined?" → "Merelani Hills [3]", where [3] is about Tanzanian diamonds).

This experiment changes **only the model**. Chunks (app chunker), k, prompt, temperature, dataset, evaluators and repetitions are the same as in Part 5. The `gpt-4.1-mini` arm is exactly Part 5's `B-app-chunker-k8`, so its results are reused rather than run again.

| Experiment | Model | Price per 1M tokens (input / output) |
|---|---|---|
| `M-gpt-4o-mini` | gpt-4o-mini | $0.15 / $0.60 |
| `M-gpt-4.1-mini` | gpt-4.1-mini (app) | $0.40 / $1.60 |

Prices are from third-party trackers as of October 2026; check OpenAI's pricing page.

**Hypothesis:** `gpt-4.1-mini` scores higher on the unanswerable questions and on groundedness, with little difference on questions the corpus answers.

In [15]:
BASELINE_MODEL = "gpt-4o-mini"
assert APP_MODEL != BASELINE_MODEL, "the app already uses the baseline model"

# The app-model arm is identical to Part 5's B-app-chunker-k8, so reuse it instead of re-running.
model_results = {f"M-{APP_MODEL}": results[f"B-app-chunker-k{APP_TOP_K}"]}

name = f"M-{BASELINE_MODEL}"
print(f"=== {name} ===")
model_results = {
    name: evaluate(
        make_target(stores["B"], APP_TOP_K, model=BASELINE_MODEL),
        data=DATASET_NAME,
        evaluators=evaluators,
        experiment_prefix=name,
        metadata={"chunks": "app-chunker", "k": APP_TOP_K, "model": BASELINE_MODEL},
        num_repetitions=N_REPS,
        max_concurrency=4,
    ),
    **model_results,
}

=== M-gpt-4o-mini ===

View the evaluation results for experiment: 'M-gpt-4o-mini-0738a313' at:
https://smith.langchain.com/o/52420107-7b88-4243-acba-2f92a36f9bc4/datasets/822dec15-b523-4bde-b365-8caa17350b91/compare?selectedSessions=819190c1-1ace-4f91-914e-61caafd7f837

0it [00:00, ?it/s]

1it [00:07,  7.34s/it]

2it [00:07,  3.17s/it]

3it [00:11,  3.40s/it]

5it [00:12,  1.96s/it]

7it [00:15,  1.73s/it]

8it [00:17,  1.61s/it]

9it [00:19,  1.69s/it]

10it [00:20,  1.73s/it]

11it [00:21,  1.56s/it]

12it [00:24,  1.80s/it]

13it [00:25,  1.48s/it]

14it [00:28,  2.11s/it]

15it [00:29,  1.62s/it]

16it [00:30,  1.66s/it]

17it [00:33,  1.84s/it]

18it [00:34,  1.67s/it]

19it [00:35,  1.54s/it]

20it [00:37,  1.64s/it]

21it [00:38,  1.45s/it]

23it [00:43,  1.85s/it]

24it [00:43,  1.45s/it]

25it [00:43,  1.22s/it]

26it [00:45,  1.27s/it]

27it [00:49,  1.95s/it]

28it [00:50,  1.88s/it]

30it [00:53,  1.61s/it]

31it [00:56,  2.08s/it]

32it [00:58,  1.91s/it]

33it [00:58,  1.47s/it]

34it [01:00,  1.70s/it]

35it [01:03,  2.02s/it]

36it [01:04,  1.79s/it]

37it [01:05,  1.54s/it]

38it [01:08,  1.80s/it]

38it [01:08,  1.80s/it]

In [16]:
model_rows = pd.concat([to_frame(name, res) for name, res in model_results.items()], ignore_index=True)
for m in METRICS:
    model_rows[m] = pd.to_numeric(model_rows[m], errors="coerce")

model_rows["answerable"] = model_rows["category"].ne("unanswerable").map({True: "answerable", False: "unanswerable"})
print("Overall:")
display(model_rows.groupby("experiment", sort=False)[METRICS].mean().round(2))
print("Answerable vs unanswerable (correctness / groundedness):")
display(
    model_rows.groupby(["answerable", "experiment"], sort=False)[["correctness", "groundedness"]]
    .mean()
    .round(2)
    .unstack("experiment")
)
print("Per run:")
display(model_rows.groupby(["experiment", "rep"], sort=False)[METRICS].mean().round(2))

Overall:

,correctness,helpfulness,groundedness,citation_accuracy,retrieval_hit
experiment,,,,,
M-gpt-4o-mini,0.95,0.92,0.82,0.97,1.0
M-gpt-4.1-mini,1.00,1.00,0.95,0.98,1.0

Answerable vs unanswerable (correctness / groundedness):

               correctness                 groundedness
experiment   M-gpt-4o-mini M-gpt-4.1-mini M-gpt-4o-mini M-gpt-4.1-mini
answerable
unanswerable          0.67            1.0          0.67           1.00
answerable            1.00            1.0          0.84           0.94

Per run:

                    correctness  helpfulness  groundedness  citation_accuracy  \
experiment     rep
M-gpt-4o-mini  1           0.95         0.89          0.79               0.97
               2           0.95         0.95          0.84               0.96
M-gpt-4.1-mini 1           1.00         1.00          0.95               0.97
               2           1.00         1.00          0.95               0.99

                    retrieval_hit
experiment     rep
M-gpt-4o-mini  1              1.0
               2              1.0
M-gpt-4.1-mini 1              1.0
               2              1.0

Unanswerable questions, answer by answer:

In [17]:
unanswerable = model_rows[model_rows["category"] == "unanswerable"]
unanswerable[["experiment", "rep", "question", "correctness", "groundedness", "outputs.output"]].sort_values(
    ["question", "experiment", "rep"]
)

,experiment,rep,question,correctness,groundedness,outputs.output
38,M-gpt-4.1-mini,1,How much does a carat of tanzanite cost?,1,1,The sources I found do not provide specific information on the cost per carat of tanzanite. They include detailed lists of gemstones in the Smithsonian collection and some general information abou...
59,M-gpt-4.1-mini,2,How much does a carat of tanzanite cost?,1,1,The sources I retrieved do not provide specific information on the cost of a carat of tanzanite. They include detailed lists of gemstones in the Smithsonian collection and some general information...
3,M-gpt-4o-mini,1,How much does a carat of tanzanite cost?,1,1,The sources do not provide specific information about the cost of tanzanite per carat. They cover various gemstones and their characteristics but do not delve into pricing details. If you're inter...
20,M-gpt-4o-mini,2,How much does a carat of tanzanite cost?,1,1,The sources do not provide specific information about the cost of tanzanite per carat. They cover various gemstones and their characteristics but do not delve into pricing details. If you're inter...
41,M-gpt-4.1-mini,1,What is the hardness of moissanite?,1,1,"The sources do not specifically mention the hardness of moissanite. They provide hardness values for other gemstones such as diamond (10 Mohs), corundum (9 Mohs), topaz (8 Mohs), and quartz (7 Moh..."
56,M-gpt-4.1-mini,2,What is the hardness of moissanite?,1,1,"The sources do not specifically mention the hardness of moissanite. They provide hardness values for other gemstones such as diamond (10 Mohs), corundum (9 Mohs), topaz (8 Mohs), and quartz (7 Moh..."
1,M-gpt-4o-mini,1,What is the hardness of moissanite?,1,1,"The sources do not specifically mention the hardness of moissanite. However, they do provide information on the Mohs scale of hardness, which ranks various gemstones. For example, diamond is rated..."
21,M-gpt-4o-mini,2,What is the hardness of moissanite?,1,1,"The sources do not specifically mention the hardness of moissanite. However, they provide information on the Mohs scale of hardness, which ranks various gemstones. For example, diamond is rated as..."
39,M-gpt-4.1-mini,1,Where is tanzanite mined?,1,1,"The sources do not specifically mention where tanzanite is mined. They cover information about other gemstones such as tourmaline, diamond, spodumene, and quartz, including their locations and cha..."
57,M-gpt-4.1-mini,2,Where is tanzanite mined?,1,1,"The sources do not specifically mention where tanzanite is mined. They cover information about other gemstones such as tourmaline, diamond, spodumene, and quartz, including their locations and cha..."
0,M-gpt-4o-mini,1,Where is tanzanite mined?,0,0,"The sources do not provide specific information about where tanzanite is mined. However, tanzanite is primarily found in Tanzania, particularly in the Merelani Hills near Mount Kilimanjaro. If you..."
19,M-gpt-4o-mini,2,Where is tanzanite mined?,0,0,"The sources do not provide specific information about where tanzanite is mined. However, tanzanite is primarily found in Tanzania, specifically in the Merelani Hills near Mount Kilimanjaro. If you..."

## Part 6: Does the app decide correctly when to search?

The pipeline above always retrieves. In the app the model chooses whether to call `getInformation`, so this part sends messages to the running app's `/api/chat` and checks the stream for a tool call (lines starting with `9:`). Each case runs twice; the pause keeps under the app's rate limit (10 requests/minute).

In [18]:
import time

import requests

APP_URL = os.environ.get("APP_URL", "http://localhost:3000")

SAPPHIRE_TURN = [
    {"role": "user", "content": "What color is sapphire?"},
    {"role": "assistant", "content": "Sapphires are most commonly blue."},
]
cases = [
    ("hi!", [{"role": "user", "content": "hi!"}], False),
    ("what can you do?", [{"role": "user", "content": "what can you do?"}], False),
    ("thanks (follow-up)", SAPPHIRE_TURN + [{"role": "user", "content": "thanks, that helps!"}], False),
    ("How do I cook carbonara?", [{"role": "user", "content": "How do I cook carbonara?"}], False),
    ("What color is sapphire?", [{"role": "user", "content": "What color is sapphire?"}], True),
    ("is my stone good?", [{"role": "user", "content": "is my stone good?"}], True),
]


def ask_app(messages):
    stream = requests.post(f"{APP_URL}/api/chat", json={"messages": messages}, timeout=90).text.splitlines()
    searched = any(line.startswith("9:") for line in stream)
    text = "".join(json.loads(line[2:]) for line in stream if line.startswith("0:"))
    return searched, text


try:
    requests.get(APP_URL, timeout=5)
except requests.RequestException:
    print(f"App not reachable at {APP_URL}; start it with `npm run dev` and re-run this cell.")
else:
    tool_rows = []
    for label, messages, should_search in cases:
        for attempt in (1, 2):
            searched, text = ask_app(messages)
            tool_rows.append({"message": label, "attempt": attempt, "should_search": should_search,
                              "searched": searched, "correct": searched == should_search, "reply": text[:120]})
            time.sleep(7)
    tool_df = pd.DataFrame(tool_rows)
    print(f"Correct search decisions: {tool_df['correct'].sum()}/{len(tool_df)}")
    display(tool_df)

Correct search decisions: 12/12

,message,attempt,should_search,searched,correct,reply
0,hi!,1,False,False,True,"Hello! How can I help you with gemstones today? You can ask me about gemstone properties, how to identify different gems"
1,hi!,2,False,False,True,"Hello! How can I help you with gemstones today? You can ask me about gemstone properties, how to identify different gems"
2,what can you do?,1,False,False,True,"Hello! I can help you with information about gemstones, including their properties, identification, history, famous gems"
3,what can you do?,2,False,False,True,"Hello! I can help you with information about gemstones, including their properties, identification, history, famous gems"
4,thanks (follow-up),1,False,False,True,"You're welcome! If you're curious, you can ask me about different types of sapphires, how to identify them, or where the"
5,thanks (follow-up),2,False,False,True,"You're welcome! If you're curious, you can ask me about different types of sapphires, how to identify them, or where the"
6,How do I cook carbonara?,1,False,False,True,"I can only help with gemstone-related questions. Try asking me about gemstone properties, identification, or history!"
7,How do I cook carbonara?,2,False,False,True,"I can only help with gemstone-related questions. Try asking me about gemstone properties, identification, or history!"
8,What color is sapphire?,1,True,True,True,"Sapphire can be found in a variety of colors including blue, yellow, pink, green, colorless, and any color except red. T"
9,What color is sapphire?,2,True,True,True,"Sapphire can be found in a variety of colors including blue, yellow, pink, green, colorless, and any color except red. T"
10,is my stone good?,1,True,True,True,"To evaluate if your stone is good as a gemstone, several qualities are considered: brilliance, beauty, durability, rarit"
11,is my stone good?,2,True,True,True,"To evaluate if your stone is good as a gemstone, several qualities are considered: brilliance, beauty, durability, rarit"

## Part 7: Conclusion

All experiments use the app's current prompt and temperature 0, with 19 questions × 2 runs each.

### Chunking (Part 5, on `gpt-4.1-mini`)

| Metric | A: old splitter, k=8 | **B: app chunker, k=8** | B: app chunker, k=4 |
|---|---|---|---|
| Correctness | 0.95 | **1.00** | 0.95 |
| Helpfulness | 0.95 | **1.00** | 0.92 |
| Groundedness (vs retrieved passages) | 0.95 | 0.95 | 0.89 |
| Citation accuracy | 1.00 | 0.98 | 0.95 |
| Retrieval hit | 0.94 | **1.00** | 1.00 |

1. **The app chunker fixes catalog lookups.** In both runs, A didn't retrieve the catalog passage for "largest topaz in the Smithsonian collection list" (its chunk has the rows cut off from the TOPAZ heading) and answered that the sources don't say. B answered "7,725 carats, yellow, Brazil" both times. That accounts for the retrieval gap (0.94 → 1.00) and B's perfect correctness.
2. **Otherwise A and B are close.** Groundedness is tied and citation accuracy is within noise. The chunker's case rests on the catalog result, which is deterministic.
3. **Keep k=8.** At k=4, "Where does the US import most of its diamonds from?" failed in both runs: the import-sources table didn't make the top 4.

### Model (Part 5b, app chunker, k=8)

| Metric | gpt-4o-mini | **gpt-4.1-mini** |
|---|---|---|
| Correctness | 0.95 | **1.00** |
| Helpfulness | 0.92 | **1.00** |
| Groundedness | 0.82 | **0.95** |
| — on answerable questions | 0.84 | **0.94** |
| — on unanswerable questions | 0.67 | **1.00** |
| Citation accuracy | 0.97 | 0.98 |
| Cost per 1,000 gem questions (measured tokens) | ~$0.52 | ~$1.39 |

4. **`gpt-4.1-mini` is more grounded, and the gap is larger than the noise.** Groundedness was 0.79 and 0.84 across `gpt-4o-mini`'s two runs, and 0.95 in both of `gpt-4.1-mini`'s.
5. **The tanzanite trap separates them.** For "Where is tanzanite mined?" (the corpus mentions Tanzania, never tanzanite), `gpt-4o-mini` answered from its own knowledge in both runs; `gpt-4.1-mini` said the sources don't cover it both times.
6. **The prompt fix worked on both models.** "What is the hardness of moissanite?" used to get "the sources don't cover it… however, it's generally known to be 9.25". With the new rule and temperature 0, both models stopped after saying the sources don't cover it, in every run.
7. **Cost:** ~2.7× per question, about $0.87 more per 1,000 questions at this app's measured token use.

### Search decision (Part 6, live app on `gpt-4.1-mini`)

8. 12/12 correct: greetings, "what can you do?", thanks and an off-topic question got no search; gem questions, including "is my stone good?", always searched.

### Noise

With temperature 0 the runs agree much more than in earlier versions of this notebook: two runs of the same experiment scored a question differently on 0–11% of questions (previously up to 28% on citation accuracy, at the default temperature). Most of the earlier noise came from varying answers, not just the judge. Differences of one question (about 0.05) should still be treated as noise.

### Recommendation

- Keep the app as configured: structure-aware chunker, `topK: 8`, `gpt-4.1-mini` at temperature 0, with the stricter "stop when the sources don't cover it" rule.
- The model switch is worth its cost here: it's the only change that fixed answers invented from outside the corpus (tanzanite), and at this app's scale it costs cents.
- To strengthen the evaluation: add more catalog, table and "trap" questions (topics adjacent to the corpus but not in it). These are where configurations actually differ.